module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: content
      target: content
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts

params:
  persons:
    realestates_persons:
      desktop: "100x100"
      mobile: "100x100"

# Default
permalinks:
  realestates_persons: /realestates/agents/:slug/
taxonomies:
  realestates_person: realestates_persons