module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: content
      target: content
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts

# Default
permalinks:
  realestates_persons: /realestates/agents/:slug/
taxonomies:
  realestates_person: realestates_persons